### ISSUE TITLE
Infinity in feed status

### ISSUE THREAD

**Issue by jannyba** [synzen/MonitoRSS-Web#6]
Hi

please fix the "infinity" number, thanks 👍 

![image](https://user-images.githubusercontent.com/56595831/90342782-22b87f00-e00b-11ea-88af-0ac396c4eed9.png)

**Comment by synzen** [comment]
Hi, I cannot reproduce your issue. Please report your version (found in package.json in your pulled files), as well as your `config.feeds` values

**Comment by jannyba** [comment]
This was happening with non-valid feed, so Refresh rate cannot be determined. I will leave this on the server for you to examine.

**Comment by synzen** [comment]
I am unable to reproduce your issue

![image](https://user-images.githubusercontent.com/18688793/90519667-56dc8e80-e136-11ea-822f-fafe8f5f0568.png)

Please report your version (found in package.json in your pulled files), as well as your `config.feeds` values

**Comment by jannyba** [comment]
Hello

please insert a valid rss link and then make the link (on its server) invalid. For example I'm using http auth name and password in the link, and when I changed the password, it happens.

**Comment by synzen** [comment]
Please report your version (found in package.json in your pulled files), as well as your config.feeds values for me to be able to reproduce your issue

**Comment by jannyba** [comment]
can't reproduce anymore :(
